<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Rize\\UriTemplate' => array($vendorDir . '/rize/uri-template/src'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
